version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/apps/iot
hooks:
  ApplicationStart:
   - location: scripts/application_start.sh
     timeout: 2000
     runas: root
deployment:
  terminationWaitTimeInMinutes: 1
